### Site Settings ###
title               : drd Blog
description         : >-
                      ❤<br>
                      컴퓨터라는 세계 안에서<br>
                      내가 만든 프로그램이 동작할 때<br>
                      즐거움을 느끼는 개발자<br>
baseurl             : "/"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : gaeundev/gaeundev.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
# remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/docs.md
  - documentation/elements.html
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : LEE GA EUN
  image             : palm-tree.png
#  behance           : your_username
# dribbble          : your_username
  email             : drd92dev@gmail.com
#  facebook          : your_username
  github            : gaeundev
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
#  linkedin          : your_username
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : drd92_dev
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus: your-short-name-disqus                          # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
